import type { Lot } from "@/types";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const now = () => Date.now();

// 실제 API(GET /api/artworks, GET /api/auctions/{id}/current-price 등)가 데이터를
// 채우기 전까지 화면을 완성해두기 위한 목데이터입니다. PoC 단순화를 위해
// artwork.id === auction.id === auction.artworkId 로 맞춰뒀습니다.
export const MOCK_LOTS: Lot[] = [
  {
    artwork: {
      id: 1,
      consignorId: 101,
      title: "고요한 파동",
      startPrice: 3_000_000,
      estimatedPrice: 6_000_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-1/900/1100",
      status: "IN_AUCTION",
    },
    auction: {
      id: 1,
      artworkId: 1,
      startPrice: 3_000_000,
      currentPrice: 5_200_000,
      minBidUnit: 100_000,
      previewStart: new Date(now() - 3 * DAY).toISOString(),
      previewEnd: new Date(now() - 1 * HOUR).toISOString(),
      auctionEndAt: new Date(now() + 2 * HOUR + 14 * 60 * 1000).toISOString(),
      status: "ONGOING",
    },
    artistName: "김서연",
    category: "회화 · 캔버스에 유채",
    description:
      "빛이 수면 위로 흩어지는 순간을 겹겹의 유채 붓질로 쌓아올린 작품입니다. 3일간의 프리뷰 동안 다수의 사전 관심 등록을 받았습니다.",
    images: [
      "https://picsum.photos/seed/artbid-1/900/1100",
      "https://picsum.photos/seed/artbid-1b/900/1100",
      "https://picsum.photos/seed/artbid-1c/900/1100",
    ],
    bidCount: 18,
    viewerCount: 142,
    isMock: true,
  },
  {
    artwork: {
      id: 2,
      consignorId: 102,
      title: "밤의 정원",
      startPrice: 1_500_000,
      estimatedPrice: 3_200_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-2/900/1100",
      status: "IN_AUCTION",
    },
    auction: {
      id: 2,
      artworkId: 2,
      startPrice: 1_500_000,
      currentPrice: 2_980_000,
      minBidUnit: 50_000,
      previewStart: new Date(now() - 2 * DAY).toISOString(),
      previewEnd: new Date(now() - 2 * HOUR).toISOString(),
      auctionEndAt: new Date(now() + 22 * 1000).toISOString(),
      status: "EXTENDED",
    },
    artistName: "이도현",
    category: "사진 · 아카이벌 피그먼트 프린트",
    description:
      "마감 30초 전 입찰이 들어와 안티 스나이핑 규칙으로 마감이 자동 연장된 상태입니다. 지금 입찰하면 마감이 다시 30초 늘어납니다.",
    images: [
      "https://picsum.photos/seed/artbid-2/900/1100",
      "https://picsum.photos/seed/artbid-2b/900/1100",
    ],
    bidCount: 31,
    viewerCount: 266,
    isMock: true,
  },
  {
    artwork: {
      id: 3,
      consignorId: 103,
      title: "부유하는 기억",
      startPrice: 4_500_000,
      estimatedPrice: 8_000_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-3/900/1100",
      status: "PREVIEW",
    },
    auction: {
      id: 3,
      artworkId: 3,
      startPrice: 4_500_000,
      currentPrice: 4_500_000,
      minBidUnit: 200_000,
      previewStart: new Date(now() - 6 * HOUR).toISOString(),
      previewEnd: new Date(now() + 2 * DAY).toISOString(),
      auctionEndAt: new Date(now() + 2 * DAY + 3 * HOUR).toISOString(),
      status: "PREVIEW",
    },
    artistName: "박지민",
    category: "조각 · 브론즈",
    description: "프리뷰 기간 동안 3D 뷰어로 360도 감상할 수 있습니다. 경매는 프리뷰 종료 후 시작됩니다.",
    images: [
      "https://picsum.photos/seed/artbid-3/900/1100",
      "https://picsum.photos/seed/artbid-3b/900/1100",
    ],
    bidCount: 0,
    viewerCount: 58,
    isMock: true,
  },
  {
    artwork: {
      id: 4,
      consignorId: 104,
      title: "유리의 결",
      startPrice: 2_200_000,
      estimatedPrice: 4_000_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-4/900/1100",
      status: "PREVIEW",
    },
    auction: {
      id: 4,
      artworkId: 4,
      startPrice: 2_200_000,
      currentPrice: 2_200_000,
      minBidUnit: 100_000,
      previewStart: new Date(now() - 1 * DAY).toISOString(),
      previewEnd: new Date(now() + 5 * HOUR).toISOString(),
      auctionEndAt: new Date(now() + 8 * HOUR).toISOString(),
      status: "SCHEDULED",
    },
    artistName: "한소이",
    category: "미디어아트 · 3D 모델",
    description:
      "3D 뷰어 데모용 작품입니다. 실물 스캔 데이터 등록 전까지는 샘플 3D 모델(duck.glb)로 뷰어 동작을 확인할 수 있습니다.",
    images: [
      "https://picsum.photos/seed/artbid-4/900/1100",
      "https://picsum.photos/seed/artbid-4b/900/1100",
    ],
    bidCount: 0,
    viewerCount: 21,
    isMock: true,
  },
  {
    artwork: {
      id: 5,
      consignorId: 105,
      title: "정적 속으로",
      startPrice: 1_800_000,
      estimatedPrice: 3_000_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-5/900/1100",
      status: "SOLD",
    },
    auction: {
      id: 5,
      artworkId: 5,
      startPrice: 1_800_000,
      currentPrice: 3_450_000,
      minBidUnit: 100_000,
      previewStart: new Date(now() - 7 * DAY).toISOString(),
      previewEnd: new Date(now() - 5 * DAY).toISOString(),
      auctionEndAt: new Date(now() - 4 * DAY).toISOString(),
      status: "CLOSED",
    },
    artistName: "최윤아",
    category: "판화 · 목판",
    description: "총 24건의 입찰 끝에 시작가 대비 91% 높은 가격에 낙찰된 작품입니다.",
    images: ["https://picsum.photos/seed/artbid-5/900/1100"],
    bidCount: 24,
    viewerCount: 0,
    isMock: true,
  },
  {
    artwork: {
      id: 6,
      consignorId: 106,
      title: "붉은 지평선",
      startPrice: 5_000_000,
      estimatedPrice: 9_500_000,
      certificateUrl: null,
      imageUrl: "https://picsum.photos/seed/artbid-6/900/1100",
      status: "SOLD",
    },
    auction: {
      id: 6,
      artworkId: 6,
      startPrice: 5_000_000,
      currentPrice: 9_800_000,
      minBidUnit: 200_000,
      previewStart: new Date(now() - 10 * DAY).toISOString(),
      previewEnd: new Date(now() - 8 * DAY).toISOString(),
      auctionEndAt: new Date(now() - 7 * DAY).toISOString(),
      status: "CLOSED",
    },
    artistName: "정하늘",
    category: "회화 · 캔버스에 아크릴",
    description: "추정가 상단을 넘어선 가격에 낙찰된 이번 시즌 최고가 작품입니다.",
    images: ["https://picsum.photos/seed/artbid-6/900/1100"],
    bidCount: 37,
    viewerCount: 0,
    isMock: true,
  },
];

export function getMockLot(id: number): Lot | undefined {
  return MOCK_LOTS.find((lot) => lot.artwork.id === id);
}
